name: Auto EUserv

on:
  schedule:
    - cron: '0 4 * * *'  # 每天 UTC 时间 04:00 运行，对应于 UTC+8 时间的每天中午 12:00
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 指定Python3.x

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script
      env:
        EUSERV_USERNAME: zhayuyang0427@gmail.com
        EUSERV_PASSWORD: Stevie1234!
        TRUECAPTCHA_USERID: demo-user-1
        TRUECAPTCHA_APIKEY: soyxMWnziLzPHUgjYw9i
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        MAILPARSER_DOWNLOAD_URL_ID: hcpmdyvh
      run: python Github_Action.py
